import React from 'react'

import MatchModal from './'

export default {
  title: 'Редактор матча',
  component: MatchModal,
  argTypes: {}
}

const Template = (args) => <MatchModal {...args} />

export const Default = Template.bind({});
Default.args = {
    match:{
    _id: "62ffb3f05af15e278172e346",
    date: "21-08-08",
    time: "17:30",
    remote: null,
    origin: {
        id: "27726",
        link: "https://olesports.ru/football/matches/27726",
        source: "ole"
    },
    scores: {
        full: {
            home: "2",
            away: "1"
        }
    },
    broadcastURL: null,
    fake: false,
    matchdayId: "62ffb3f05af15e278172e343",
    stageId: "62ffb36a5af15e278172dc0d",
    homeId: "62ff5c93e5e918239432dcda",
    awayId: "62fe53da34134c11a93c842f",
    __v: 0,
    stage: {
        _id: "62ffb36a5af15e278172dc0d",
        title: "Дивизион A",
        type: "round",
        emblem: "false",
        tournamentId: "62ffb3695af15e278172dc0a",
        order: null,
        rules: null,
        parentId: null,
        seasonId: null,
        remote: null,
        origin: {
            id: "sumcup21",
            source: "ole"
        },
        roundsQty: 1,
        federationId: "624c17e25887f52dbfc6819c",
        leagueId: "62f37ff77eabb391c6e2314e",
        finished: true,
        excluded: null,
        __v: 0,
        tournament: {
            _id: "62ffb3695af15e278172dc0a",
            name: "Летний кубок — 2021",
            finished: true,
            seasonId: "62ffae105af15e27817280e9",
            federationId: "624c17e25887f52dbfc6819c",
            leagueId: "62f37ff77eabb391c6e2314e",
            emblem: null,
            config: {
                disqual: {
                    yellow: {
                        qty: 4,
                        count: 1
                    },
                    red: {
                        qty: 1,
                        count: 1
                    },
                    redAsTwoYellow: false,
                    transition: false
                }
            },
            remote: null,
            origin: {
                link: "https://olesports.ru/football/Pervenstvo/sumcup21",
                id: "sumcup21",
                source: "ole"
            },
            data: null,
            order: 0,
            sponsorship: null,
            __v: 0
        },
        federation: {
            _id: "624c17e25887f52dbfc6819c",
            name: "OLE Promo",
            emblem: "",
            code: "",
            sporttypeId: "623b14fe3aac1773a551604f",
            legacyId: "606f1b571d4588670727d825"
        }
    },
    home: {
        _id: "62ff5c93e5e918239432dcda",
        name: "Атлант МО Дачное",
        clubId: "62ff5c93e5e918239432dcd8",
        isActive: true,
        age: null,
        canonical: true,
        __v: 0,
        roster: {
            _id: "62ffb3f15af15e278172e348",
            matchId: "62ffb3f05af15e278172e346",
            teamId: "62ff5c93e5e918239432dcda",
            players: [
                {
                    _id: "62fe48e660710a0b7a9702a7",
                    name: "Евгений",
                    surname: "Алдухов",
                    middlename: "Александрович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/alduhov_e20_atlantdachnoe.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "1232",
                        link: "https://olesports.ru/profiles/players/1232"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Алдухов Евгений Александрович"
                },
                {
                    _id: "62ffa9335af15e2781723297",
                    name: "Дмитрий",
                    surname: "Анищенков",
                    middlename: "Витальевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/AnischenkovD_AtlantMODachnoe_osen2020.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "18982",
                        link: "https://olesports.ru/profiles/players/18982"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Анищенков Дмитрий Витальевич"
                },
                {
                    _id: "62ff5ca5e5e918239432ddc6",
                    name: "Лев",
                    surname: "Аронов",
                    middlename: "Евгеньевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/Aronov_AtlantMO21.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "10739",
                        link: "https://olesports.ru/profiles/players/10739"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Аронов Лев Евгеньевич"
                },
                {
                    _id: "62fe9772375a1c1d6366d787",
                    name: "Евгений",
                    surname: "Ганжа",
                    middlename: "Сергеевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/VTB/ganja20_pingv.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "5724",
                        link: "https://olesports.ru/profiles/players/5724"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Ганжа Евгений Сергеевич"
                },
                {
                    _id: "62ffaf8a5af15e27817295e6",
                    name: "Вячеслав",
                    surname: "Гребенщиков",
                    middlename: "Александрович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "19029",
                        link: "https://olesports.ru/profiles/players/19029"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Гребенщиков Вячеслав Александрович"
                },
                {
                    _id: "62ff422da2d7241a652608b7",
                    name: "Давид",
                    surname: "Колбаия",
                    middlename: "Отариевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Fortuna2003/kolbaia_fortunagf.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "10255",
                        link: "https://olesports.ru/profiles/players/10255"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Колбаия Давид Отариевич"
                },
                {
                    _id: "62ff7dd95af15e27816f6c51",
                    name: "Сергей",
                    surname: "Копалиани",
                    middlename: "Нугзарович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "11572",
                        link: "https://olesports.ru/profiles/players/11572"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Копалиани Сергей Нугзарович"
                },
                {
                    _id: "62ff570a4e0d681d80aac4e3",
                    name: "Дмитрий",
                    surname: "Кушнир",
                    middlename: "Юрьевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Rabona/kushnir21_rabona.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "11646",
                        link: "https://olesports.ru/profiles/players/11646"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Кушнир Дмитрий Юрьевич"
                },
                {
                    _id: "62ff715d5af15e27816e71f2",
                    name: "Расул",
                    surname: "Магомедов",
                    middlename: "Рафикович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/KafeItaliy/magamedov20_topdeal.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "13838",
                        link: "https://olesports.ru/profiles/players/13838"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Магомедов Расул Рафикович"
                },
                {
                    _id: "62ff9e8a5af15e2781718bb9",
                    name: "Зейн",
                    surname: "Мамчуев",
                    middlename: "",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "18393",
                        link: "https://olesports.ru/profiles/players/18393"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Мамчуев Зейн"
                },
                {
                    _id: "62fe9bb4375a1c1d6366fd07",
                    name: "Константин",
                    surname: "Морозов",
                    middlename: "Сергеевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/Morozov_AtlantMO21.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "2716",
                        link: "https://olesports.ru/profiles/players/2716"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Морозов Константин Сергеевич"
                },
                {
                    _id: "62ffb3865af15e278172dcfb",
                    name: "Илья",
                    surname: "Мухин",
                    middlename: "Игоревич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "1235",
                        link: "https://olesports.ru/profiles/players/1235"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Мухин Илья Игоревич"
                },
                {
                    _id: "62ff79f75af15e27816f2211",
                    name: "Николай",
                    surname: "Николаев",
                    middlename: "Александрович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "13218",
                        link: "https://olesports.ru/profiles/players/13218"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Николаев Николай Александрович"
                }
            ],
            __v: 0
        },
        squad: {
            _id: "62ffb3875af15e278172dd03",
            openDate: "21-07-11",
            closeDate: null,
            remote: null,
            tournamentId: "62ffb3695af15e278172dc0a",
            teamId: "62ff5c93e5e918239432dcda",
            players: [
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe48e660710a0b7a9702a7",
                    player: {
                        _id: "62fe48e660710a0b7a9702a7",
                        name: "Евгений",
                        surname: "Алдухов",
                        middlename: "Александрович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/alduhov_e20_atlantdachnoe.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "1232",
                            link: "https://olesports.ru/profiles/players/1232"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff5ca5e5e918239432ddc6",
                    player: {
                        _id: "62ff5ca5e5e918239432ddc6",
                        name: "Лев",
                        surname: "Аронов",
                        middlename: "Евгеньевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/Aronov_AtlantMO21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "10739",
                            link: "https://olesports.ru/profiles/players/10739"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe98c5375a1c1d6366e163",
                    player: {
                        _id: "62fe98c5375a1c1d6366e163",
                        name: "Егор",
                        surname: "Голубев",
                        middlename: "Алексеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/Golubev_AtlantMO21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "5629",
                            link: "https://olesports.ru/profiles/players/5629"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffaf8a5af15e27817295e6",
                    player: {
                        _id: "62ffaf8a5af15e27817295e6",
                        name: "Вячеслав",
                        surname: "Гребенщиков",
                        middlename: "Александрович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "19029",
                            link: "https://olesports.ru/profiles/players/19029"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fea4e59c26801f955ef105",
                    player: {
                        _id: "62fea4e59c26801f955ef105",
                        name: "Даниил",
                        surname: "Ефимов",
                        middlename: "Сергеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/efimov19_atlant.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "400",
                            link: "https://olesports.ru/profiles/players/400"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff61bf5af15e27816d7625",
                    player: {
                        _id: "62ff61bf5af15e27816d7625",
                        name: "Артур",
                        surname: "Ламанов",
                        middlename: "Николаевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/LomInvest/lamanov21au_promrenova.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "11033",
                            link: "https://olesports.ru/profiles/players/11033"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe9bb4375a1c1d6366fd07",
                    player: {
                        _id: "62fe9bb4375a1c1d6366fd07",
                        name: "Константин",
                        surname: "Морозов",
                        middlename: "Сергеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/Morozov_AtlantMO21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "2716",
                            link: "https://olesports.ru/profiles/players/2716"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff930a5af15e278170d276",
                    player: {
                        _id: "62ff930a5af15e278170d276",
                        name: "Николай",
                        surname: "Раков",
                        middlename: "Андреевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/rakov_n20_atlantdachnoe.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "16390",
                            link: "https://olesports.ru/profiles/players/16390"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffb3855af15e278172dcf2",
                    player: {
                        _id: "62ffb3855af15e278172dcf2",
                        name: "Максим",
                        surname: "Бакланов",
                        middlename: "Михайлович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "19962",
                            link: "https://olesports.ru/profiles/players/19962"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff570a4e0d681d80aac4e3",
                    player: {
                        _id: "62ff570a4e0d681d80aac4e3",
                        name: "Дмитрий",
                        surname: "Кушнир",
                        middlename: "Юрьевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Rabona/kushnir21_rabona.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "11646",
                            link: "https://olesports.ru/profiles/players/11646"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff9e8a5af15e2781718bb9",
                    player: {
                        _id: "62ff9e8a5af15e2781718bb9",
                        name: "Зейн",
                        surname: "Мамчуев",
                        middlename: "",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "18393",
                            link: "https://olesports.ru/profiles/players/18393"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffb3865af15e278172dcfb",
                    player: {
                        _id: "62ffb3865af15e278172dcfb",
                        name: "Илья",
                        surname: "Мухин",
                        middlename: "Игоревич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "1235",
                            link: "https://olesports.ru/profiles/players/1235"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff79f75af15e27816f2211",
                    player: {
                        _id: "62ff79f75af15e27816f2211",
                        name: "Николай",
                        surname: "Николаев",
                        middlename: "Александрович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "13218",
                            link: "https://olesports.ru/profiles/players/13218"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffa3525af15e278171e3aa",
                    player: {
                        _id: "62ffa3525af15e278171e3aa",
                        name: "Михаил",
                        surname: "Покровский",
                        middlename: "Андреевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "16989",
                            link: "https://olesports.ru/profiles/players/16989"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff5ca7e5e918239432ddcf",
                    player: {
                        _id: "62ff5ca7e5e918239432ddcf",
                        name: "Александр",
                        surname: "Харитошин",
                        middlename: "Игоревич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/Haritoshin_AtlantMO21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "7964",
                            link: "https://olesports.ru/profiles/players/7964"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-25",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffb3845af15e278172dcee",
                    player: {
                        _id: "62ffb3845af15e278172dcee",
                        name: "Назар",
                        surname: "Артамонов",
                        middlename: "Сергеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "19701",
                            link: "https://olesports.ru/profiles/players/19701"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-25",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe514534134c11a93c6f56",
                    player: {
                        _id: "62fe514534134c11a93c6f56",
                        name: "Роман",
                        surname: "Овчинников",
                        middlename: "Константинович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "491",
                            link: "https://olesports.ru/profiles/players/491"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-25",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff5c96e5e918239432dcf5",
                    player: {
                        _id: "62ff5c96e5e918239432dcf5",
                        name: "Михаил",
                        surname: "Струмицкий",
                        middlename: "Вадимович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "10736",
                            link: "https://olesports.ru/profiles/players/10736"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-25",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffb3ab5af15e278172de50",
                    player: {
                        _id: "62ffb3ab5af15e278172de50",
                        name: "Никита",
                        surname: "Чуднов",
                        middlename: "Андреевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/Chudnov_AtlantMO21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "19963",
                            link: "https://olesports.ru/profiles/players/19963"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-08",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffa9335af15e2781723297",
                    player: {
                        _id: "62ffa9335af15e2781723297",
                        name: "Дмитрий",
                        surname: "Анищенков",
                        middlename: "Витальевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/AnischenkovD_AtlantMODachnoe_osen2020.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "18982",
                            link: "https://olesports.ru/profiles/players/18982"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-08",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe9772375a1c1d6366d787",
                    player: {
                        _id: "62fe9772375a1c1d6366d787",
                        name: "Евгений",
                        surname: "Ганжа",
                        middlename: "Сергеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/VTB/ganja20_pingv.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "5724",
                            link: "https://olesports.ru/profiles/players/5724"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-08",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff422da2d7241a652608b7",
                    player: {
                        _id: "62ff422da2d7241a652608b7",
                        name: "Давид",
                        surname: "Колбаия",
                        middlename: "Отариевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Fortuna2003/kolbaia_fortunagf.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "10255",
                            link: "https://olesports.ru/profiles/players/10255"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-08",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff7dd95af15e27816f6c51",
                    player: {
                        _id: "62ff7dd95af15e27816f6c51",
                        name: "Сергей",
                        surname: "Копалиани",
                        middlename: "Нугзарович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "11572",
                            link: "https://olesports.ru/profiles/players/11572"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-08",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff715d5af15e27816e71f2",
                    player: {
                        _id: "62ff715d5af15e27816e71f2",
                        name: "Расул",
                        surname: "Магомедов",
                        middlename: "Рафикович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/KafeItaliy/magamedov20_topdeal.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "13838",
                            link: "https://olesports.ru/profiles/players/13838"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-15",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62feb79db65897236266bbca",
                    player: {
                        _id: "62feb79db65897236266bbca",
                        name: "Павел",
                        surname: "Масленников",
                        middlename: "Сергеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Atlant/maslennikov18_atlant.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "7966",
                            link: "https://olesports.ru/profiles/players/7966"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                }
            ],
            __v: 0
        }
    },
    away: {
        _id: "62fe53da34134c11a93c842f",
        name: "ЮНИТЕК",
        clubId: "62fe53da34134c11a93c842d",
        isActive: true,
        age: null,
        canonical: true,
        __v: 0,
        roster: {
            _id: "62ffb3f15af15e278172e34a",
            matchId: "62ffb3f05af15e278172e346",
            teamId: "62fe53da34134c11a93c842f",
            players: [
                {
                    _id: "62ff66cd5af15e27816dce63",
                    name: "Вячеслав",
                    surname: "Байдин",
                    middlename: "Геннадьевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/baydin_v3_ekskluziv.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "12043",
                        link: "https://olesports.ru/profiles/players/12043"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Байдин Вячеслав Геннадьевич"
                },
                {
                    _id: "62ff92905af15e278170c87c",
                    name: "Алексей",
                    surname: "Белый",
                    middlename: "Леонидович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "15417",
                        link: "https://olesports.ru/profiles/players/15417"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Белый Алексей Леонидович"
                },
                {
                    _id: "62ff4b294e0d681d80aa16d9",
                    name: "Дмитрий",
                    surname: "Болтунов",
                    middlename: "Валерьевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/boltunov_unitecVesna21.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "9446",
                        link: "https://olesports.ru/profiles/players/9446"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Болтунов Дмитрий Валерьевич"
                },
                {
                    _id: "62fe9778375a1c1d6366d7b7",
                    name: "Нажмудин",
                    surname: "Везиров",
                    middlename: "Загирович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Kreativ2/vezirov_krea2Vesna22.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "688",
                        link: "https://olesports.ru/profiles/players/688"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Везиров Нажмудин Загирович"
                },
                {
                    _id: "62fe584a34134c11a93ca742",
                    name: "Дмитрий",
                    surname: "Дутко",
                    middlename: "Романович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/dutko_unitec21.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "4707",
                        link: "https://olesports.ru/profiles/players/4707"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Дутко Дмитрий Романович"
                },
                {
                    _id: "62feb1e89c26801f955f7a4e",
                    name: "Алексей",
                    surname: "Малюков",
                    middlename: "Александрович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Fortuna2003/malukov20_fortuna.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "8818",
                        link: "https://olesports.ru/profiles/players/8818"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Малюков Алексей Александрович"
                },
                {
                    _id: "62fea4ba9c26801f955eef53",
                    name: "Хуршед",
                    surname: "Мамадкулов",
                    middlename: "Курбонбоевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/mamadkylov_UniTecLeto22.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "7752",
                        link: "https://olesports.ru/profiles/players/7752"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Мамадкулов Хуршед Курбонбоевич"
                },
                {
                    _id: "62ffac095af15e278172614a",
                    name: "Игорь",
                    surname: "Панченко",
                    middlename: "Владимирович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "17350",
                        link: "https://olesports.ru/profiles/players/17350"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Панченко Игорь Владимирович"
                },
                {
                    _id: "62ffac0b5af15e278172614e",
                    name: "Дмитрий",
                    surname: "Парфенов",
                    middlename: "Игоревич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: null,
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "18721",
                        link: "https://olesports.ru/profiles/players/18721"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Парфенов Дмитрий Игоревич"
                },
                {
                    _id: "62ff858e5af15e27816febc0",
                    name: "Максим",
                    surname: "Прокопьев",
                    middlename: "Владиславович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/prokopyev_unitec21.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "14923",
                        link: "https://olesports.ru/profiles/players/14923"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Прокопьев Максим Владиславович"
                },
                {
                    _id: "62feb666b65897236266ae03",
                    name: "Сергей",
                    surname: "Соловьев",
                    middlename: "Сергеевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/19/solovev19_rayon.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "7507",
                        link: "https://olesports.ru/profiles/players/7507"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Соловьев Сергей Сергеевич"
                },
                {
                    _id: "62febc5db65897236266ea08",
                    name: "Дмитрий",
                    surname: "Фёдоров",
                    middlename: "Евгеньевич",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/fedorov_exc18.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "1425",
                        link: "https://olesports.ru/profiles/players/1425"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Фёдоров Дмитрий Евгеньевич"
                },
                {
                    _id: "62fea8ca9c26801f955f1ff2",
                    name: "Руслан",
                    surname: "Шинкуба",
                    middlename: "Гурамович",
                    countryId: null,
                    territoryId: null,
                    settlementId: null,
                    email: null,
                    birthday: null,
                    phone: null,
                    avatarUrl: "https://olesports.ru/nox-data/playerfoto/UPiter/shinkuba21au_upi.jpg",
                    woman: false,
                    remote: null,
                    photo: null,
                    origin: {
                        source: "ole",
                        id: "450",
                        link: "https://olesports.ru/profiles/players/450"
                    },
                    num: null,
                    position: null,
                    isNotDoubleOf: [],
                    __v: 0,
                    fio: "Шинкуба Руслан Гурамович"
                }
            ],
            "lineup": {
                players: [
                    {
                        _id: "62ff66cd5af15e27816dce63",
                        name: "Вячеслав",
                        surname: "Байдин",
                        middlename: "Геннадьевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/baydin_v3_ekskluziv.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "12043",
                            link: "https://olesports.ru/profiles/players/12043"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Байдин Вячеслав Геннадьевич"
                    },
                    {
                        _id: "62ff92905af15e278170c87c",
                        name: "Алексей",
                        surname: "Белый",
                        middlename: "Леонидович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "15417",
                            link: "https://olesports.ru/profiles/players/15417"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Белый Алексей Леонидович"
                    },
                    {
                        _id: "62ff4b294e0d681d80aa16d9",
                        name: "Дмитрий",
                        surname: "Болтунов",
                        middlename: "Валерьевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/boltunov_unitecVesna21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "9446",
                            link: "https://olesports.ru/profiles/players/9446"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Болтунов Дмитрий Валерьевич"
                    },
                    {
                        _id: "62fe9778375a1c1d6366d7b7",
                        name: "Нажмудин",
                        surname: "Везиров",
                        middlename: "Загирович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Kreativ2/vezirov_krea2Vesna22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "688",
                            link: "https://olesports.ru/profiles/players/688"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Везиров Нажмудин Загирович"
                    },
                    {
                        _id: "62fe584a34134c11a93ca742",
                        name: "Дмитрий",
                        surname: "Дутко",
                        middlename: "Романович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/dutko_unitec21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "4707",
                            link: "https://olesports.ru/profiles/players/4707"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Дутко Дмитрий Романович"
                    },
                    {
                        _id: "62feb1e89c26801f955f7a4e",
                        name: "Алексей",
                        surname: "Малюков",
                        middlename: "Александрович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Fortuna2003/malukov20_fortuna.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "8818",
                            link: "https://olesports.ru/profiles/players/8818"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Малюков Алексей Александрович"
                    },
                    {
                        _id: "62fea4ba9c26801f955eef53",
                        name: "Хуршед",
                        surname: "Мамадкулов",
                        middlename: "Курбонбоевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/mamadkylov_UniTecLeto22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "7752",
                            link: "https://olesports.ru/profiles/players/7752"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Мамадкулов Хуршед Курбонбоевич"
                    },
                    {
                        _id: "62ffac095af15e278172614a",
                        name: "Игорь",
                        surname: "Панченко",
                        middlename: "Владимирович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "17350",
                            link: "https://olesports.ru/profiles/players/17350"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0,
                        fio: "Панченко Игорь Владимирович"
                    }
                ],
                "formation": "1-3-2-2"
            },
            __v: 0
        },
        squad: {
            _id: "62ffb36e5af15e278172dc46",
            openDate: "21-07-11",
            closeDate: null,
            remote: null,
            tournamentId: "62ffb3695af15e278172dc0a",
            teamId: "62fe53da34134c11a93c842f",
            players: [
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff94975af15e278170eadc",
                    player: {
                        _id: "62ff94975af15e278170eadc",
                        name: "Роман",
                        surname: "Белебенцев",
                        middlename: "Сергеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/belebentsev_UniTecLeto22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "15724",
                            link: "https://olesports.ru/profiles/players/15724"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff4b294e0d681d80aa16d9",
                    player: {
                        _id: "62ff4b294e0d681d80aa16d9",
                        name: "Дмитрий",
                        surname: "Болтунов",
                        middlename: "Валерьевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/boltunov_unitecVesna21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "9446",
                            link: "https://olesports.ru/profiles/players/9446"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe584a34134c11a93ca742",
                    player: {
                        _id: "62fe584a34134c11a93ca742",
                        name: "Дмитрий",
                        surname: "Дутко",
                        middlename: "Романович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/dutko_unitec21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "4707",
                            link: "https://olesports.ru/profiles/players/4707"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe509334134c11a93c6a54",
                    player: {
                        _id: "62fe509334134c11a93c6a54",
                        name: "Дмитрий",
                        surname: "Иванов",
                        middlename: "Андреевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/ivanovD_UniTecLeto22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "1034",
                            link: "https://olesports.ru/profiles/players/1034"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffabab5af15e2781725dc8",
                    player: {
                        _id: "62ffabab5af15e2781725dc8",
                        name: "Александр",
                        surname: "Кармакулин",
                        middlename: "Эдуардович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Olimpik/karmakylin_olimpikVesna22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "18746",
                            link: "https://olesports.ru/profiles/players/18746"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff4bb84e0d681d80aa1b90",
                    player: {
                        _id: "62ff4bb84e0d681d80aa1b90",
                        name: "Даниил",
                        surname: "Ковалев",
                        middlename: "Андреевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/kovalev_UniTecLeto22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "9712",
                            link: "https://olesports.ru/profiles/players/9712"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffa3cc5af15e278171e958",
                    player: {
                        _id: "62ffa3cc5af15e278171e958",
                        name: "Руслан",
                        surname: "Коробейников",
                        middlename: "Андреевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/BCHF/korobeynikov_r20_bchf.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "17646",
                            link: "https://olesports.ru/profiles/players/17646"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fea4ba9c26801f955eef53",
                    player: {
                        _id: "62fea4ba9c26801f955eef53",
                        name: "Хуршед",
                        surname: "Мамадкулов",
                        middlename: "Курбонбоевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/mamadkylov_UniTecLeto22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "7752",
                            link: "https://olesports.ru/profiles/players/7752"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffac095af15e278172614a",
                    player: {
                        _id: "62ffac095af15e278172614a",
                        name: "Игорь",
                        surname: "Панченко",
                        middlename: "Владимирович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "17350",
                            link: "https://olesports.ru/profiles/players/17350"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff801d5af15e27816f8f62",
                    player: {
                        _id: "62ff801d5af15e27816f8f62",
                        name: "Григорий",
                        surname: "Рыженко",
                        middlename: "Олегович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/DomusGrupp/ruzenko_domus19.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "13697",
                            link: "https://olesports.ru/profiles/players/13697"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-11",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62febc5db65897236266ea08",
                    player: {
                        _id: "62febc5db65897236266ea08",
                        name: "Дмитрий",
                        surname: "Фёдоров",
                        middlename: "Евгеньевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/fedorov_exc18.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "1425",
                            link: "https://olesports.ru/profiles/players/1425"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff66cd5af15e27816dce63",
                    player: {
                        _id: "62ff66cd5af15e27816dce63",
                        name: "Вячеслав",
                        surname: "Байдин",
                        middlename: "Геннадьевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/baydin_v3_ekskluziv.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "12043",
                            link: "https://olesports.ru/profiles/players/12043"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-18",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff858e5af15e27816febc0",
                    player: {
                        _id: "62ff858e5af15e27816febc0",
                        name: "Максим",
                        surname: "Прокопьев",
                        middlename: "Владиславович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Ekskluziv/prokopyev_unitec21.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "14923",
                            link: "https://olesports.ru/profiles/players/14923"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-25",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fe9778375a1c1d6366d7b7",
                    player: {
                        _id: "62fe9778375a1c1d6366d7b7",
                        name: "Нажмудин",
                        surname: "Везиров",
                        middlename: "Загирович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Kreativ2/vezirov_krea2Vesna22.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "688",
                            link: "https://olesports.ru/profiles/players/688"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-07-25",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ffac0b5af15e278172614e",
                    player: {
                        _id: "62ffac0b5af15e278172614e",
                        name: "Дмитрий",
                        surname: "Парфенов",
                        middlename: "Игоревич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "18721",
                            link: "https://olesports.ru/profiles/players/18721"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-01",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62ff92905af15e278170c87c",
                    player: {
                        _id: "62ff92905af15e278170c87c",
                        name: "Алексей",
                        surname: "Белый",
                        middlename: "Леонидович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: null,
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "15417",
                            link: "https://olesports.ru/profiles/players/15417"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-01",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62fea8ca9c26801f955f1ff2",
                    player: {
                        _id: "62fea8ca9c26801f955f1ff2",
                        name: "Руслан",
                        surname: "Шинкуба",
                        middlename: "Гурамович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/UPiter/shinkuba21au_upi.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "450",
                            link: "https://olesports.ru/profiles/players/450"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-08",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62feb1e89c26801f955f7a4e",
                    player: {
                        _id: "62feb1e89c26801f955f7a4e",
                        name: "Алексей",
                        surname: "Малюков",
                        middlename: "Александрович",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/Fortuna2003/malukov20_fortuna.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "8818",
                            link: "https://olesports.ru/profiles/players/8818"
                        },
                        num: null,
                        position: null,
                        isNotDoubleOf: [],
                        __v: 0
                    }
                },
                {
                    linked: "21-08-08",
                    unlinked: null,
                    number: null,
                    agegroup: null,
                    position: null,
                    _id: "62feb666b65897236266ae03",
                    player: {
                        _id: "62feb666b65897236266ae03",
                        name: "Сергей",
                        surname: "Соловьев",
                        middlename: "Сергеевич",
                        countryId: null,
                        territoryId: null,
                        settlementId: null,
                        email: null,
                        birthday: null,
                        phone: null,
                        avatarUrl: "https://olesports.ru/nox-data/playerfoto/19/solovev19_rayon.jpg",
                        woman: false,
                        remote: null,
                        photo: null,
                        origin: {
                            source: "ole",
                            id: "7507",
                            link: "https://olesports.ru/profiles/players/7507"
                        },
                    nu: null,
                    positio: null,
                    isNotDoubleO: [],
                    __: 0
                    }
                }
            ],
            __v: 0
        }
    }
},
 id: '62ffb3f05af15e278172e346'

}

//
// export const Events = Template.bind({});
// Events.args = {
//     matchInfo: {
//         homeName: 'Невский',
//         awayName: 'Фортуна'
//     },
//     tabs:3,
// }

// export const Info = Template.bind({})
// Info.args = {
//     matchInfo: {
//         homeName: 'Невский',
//         awayName: 'Фортуна'
//     },
//     tabs:0,
// }
